#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_COVID
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Covidapierick")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCovid_Case(Covid_Case instance);
    partial void UpdateCovid_Case(Covid_Case instance);
    partial void DeleteCovid_Case(Covid_Case instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["CovidapierickConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Covid_Case> Covid_Cases
		{
			get
			{
				return this.GetTable<Covid_Case>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Covid_Cases")]
	public partial class Covid_Case : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Country;
		
		private System.Nullable<int> _TotalCases;
		
		private System.Nullable<int> _TotalDeths;
		
		private System.Nullable<int> _TotalRecovery;
		
		private System.Nullable<int> _TotalTests;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCountryChanging(string value);
    partial void OnCountryChanged();
    partial void OnTotalCasesChanging(System.Nullable<int> value);
    partial void OnTotalCasesChanged();
    partial void OnTotalDethsChanging(System.Nullable<int> value);
    partial void OnTotalDethsChanged();
    partial void OnTotalRecoveryChanging(System.Nullable<int> value);
    partial void OnTotalRecoveryChanged();
    partial void OnTotalTestsChanging(System.Nullable<int> value);
    partial void OnTotalTestsChanged();
    #endregion
		
		public Covid_Case()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Country
		{
			get
			{
				return this._Country;
			}
			set
			{
				if ((this._Country != value))
				{
					this.OnCountryChanging(value);
					this.SendPropertyChanging();
					this._Country = value;
					this.SendPropertyChanged("Country");
					this.OnCountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalCases", DbType="Int")]
		public System.Nullable<int> TotalCases
		{
			get
			{
				return this._TotalCases;
			}
			set
			{
				if ((this._TotalCases != value))
				{
					this.OnTotalCasesChanging(value);
					this.SendPropertyChanging();
					this._TotalCases = value;
					this.SendPropertyChanged("TotalCases");
					this.OnTotalCasesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalDeths", DbType="Int")]
		public System.Nullable<int> TotalDeths
		{
			get
			{
				return this._TotalDeths;
			}
			set
			{
				if ((this._TotalDeths != value))
				{
					this.OnTotalDethsChanging(value);
					this.SendPropertyChanging();
					this._TotalDeths = value;
					this.SendPropertyChanged("TotalDeths");
					this.OnTotalDethsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalRecovery", DbType="Int")]
		public System.Nullable<int> TotalRecovery
		{
			get
			{
				return this._TotalRecovery;
			}
			set
			{
				if ((this._TotalRecovery != value))
				{
					this.OnTotalRecoveryChanging(value);
					this.SendPropertyChanging();
					this._TotalRecovery = value;
					this.SendPropertyChanged("TotalRecovery");
					this.OnTotalRecoveryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalTests", DbType="Int")]
		public System.Nullable<int> TotalTests
		{
			get
			{
				return this._TotalTests;
			}
			set
			{
				if ((this._TotalTests != value))
				{
					this.OnTotalTestsChanging(value);
					this.SendPropertyChanging();
					this._TotalTests = value;
					this.SendPropertyChanged("TotalTests");
					this.OnTotalTestsChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
